alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
name: new-test-00
region: nyc
services:
  - build_command: yarn build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: miguelredujo/new-test-00
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    name: new-test-00
    routes:
      - path: /
    run_command: yarn start
    source_dir: /
